---
# Title: role-colobora
#
# Author: Bitfinity-NL / L. Rutten
# File: tasks/main.yml
# Original sources:
#   - https://www.collaboraoffice.com/code/linux-packages/
#
# Description:
#   Role for deploying a Collabora server.

- name: "Import the signing key"
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 0C54D189F4BA284D

- name: "Add CODE package repositories"
  apt_repository:
    repo: deb https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-ubuntu2004 ./
    filename: CollaboraOnline
    state: present

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
    
- name: "Install packages"
  apt:
    pkg:
    - apache2
    - loolwsd
    - code-brand
    - collaboraoffice*

- name: "Install packages"
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - proxy
    - proxy_wstunnel
    - proxy_http
    - ssl
    
- name: "Transfer Apache2 templates"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'collabora.conf.j2', dest: '/etc/apache2/sites-available/collabora.conf' }
    - { src: 'collabora-ssl.conf.j2', dest: '/etc/apache2/sites-available/collabora-ssl.conf' }

- name: "Enable site"
  command: a2ensite collabora
  notify: restart_apache2

- name: "Enable site"
  command: a2ensite collabora-ssl 
  notify: restart_apache2
  
- name: "Disable default site"
  command: "a2dissite {{ item }}"
  with_items:
    - 000-default
    - default-ssl
  notify: restart_apache2
  
- name: "Configure loolwsd via commandline"
  command: "{{ item }}"  
  with_items:
    - 'loolconfig set ssl.enable false'
    - 'loolconfig set ssl.termination true'
    - 'loolconfig set storage.wopi.host {{ col_loolwsd_server }}'
  notify: restart_loolwsd

- name: "Configure loolwsd via commandline"
  raw: "{{ col_loolwsd_admin }} | loolconfig set-admin-password"  
  notify: restart_loolwsd
